server:
   port: 8699

   
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      

zuul:
  routes:
    forma1:
       path: /micro-crud/**
       url: http://localhost:8899/
    forma2:
       path: /micro-mov/**
       url: http://localhost:8799/
    
       
      
   